[package]
name = "gol-rust-blank"
version = "0.1.0"
authors = ["Fredrik Ekholdt <freekh@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"